In [2]:
import pandas as pd

# 1. Load the dataset into a pandas DataFrame
df = pd.read_csv("C:\\Users\\vamsh\\Downloads\\traning\\sales_data.csv")

# 2. Display the first 5 rows of the DataFrame
print("First 5 rows of the dataset:")
print(df.head())

# 3. Check for any missing values in the dataset
print("\nMissing values in the dataset:")
print(df.isnull().sum())

# 4. Add a new column 'Total Sales' that multiplies 'Quantity Ordered' by 'Price Each'
# Assuming 'Quantity Ordered' and 'Price Each' are columns in the dataset
df['Total Sales'] = df['Quantity Ordered'] * df['Price Each']
print("\nDataset with Total Sales column added:")
print(df.head())

# 5. Find the total sales for each city and display it as a new DataFrame
# Assuming 'City' is a column in the dataset
total_sales_by_city = df.groupby('City')['Total Sales'].sum().reset_index()
print("\nTotal sales for each city:")
print(total_sales_by_city)

# 6. Identify the product with the highest total sales
# Assuming 'Product' is a column in the dataset
total_sales_by_product = df.groupby('Product')['Total Sales'].sum().reset_index()
product_highest_sales = total_sales_by_product.loc[total_sales_by_product['Total Sales'].idxmax()]
print("\nProduct with the highest total sales:")
print(product_highest_sales)

First 5 rows of the dataset:
   Order ID                     Product  Quantity Ordered  Price Each  \
0    176558        USB-C Charging Cable                 2       11.95
1    176559  Bose SoundSport Headphones                 1       99.99
2    176560                Google Phone                 1      600.00
3    176561            Wired Headphones                 3       11.99
4    176562    Lightning Charging Cable                 1       14.95

  Order Date         City
0  1/22/2023     New York
1  1/23/2023  Los Angeles
2  1/23/2023      Chicago
3  1/24/2023      Houston
4  1/24/2023     New York

Missing values in the dataset:
Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
City                0
dtype: int64

Dataset with Total Sales column added:
   Order ID                     Product  Quantity Ordered  Price Each  \
0    176558        USB-C Charging Cable                 2       11.95
1    176559  Bose SoundSport Headphones                 1       99.99
2    176560                Google Phone                 1      600.00
3    176561            Wired Headphones                 3       11.99
4    176562    Lightning Charging Cable                 1       14.95

  Order Date         City  Total Sales
0  1/22/2023     New York        23.90
1  1/23/2023  Los Angeles        99.99
2  1/23/2023      Chicago       600.00
3  1/24/2023      Houston        35.97
4  1/24/2023     New York        14.95

Total sales for each city:
            City  Total Sales
0        Chicago      1800.00
1        Houston       835.97
2    Los Angeles       115.35
3       New York        38.85
4  San Francisco      1000.00

Product with the highest total sales:
Product        ThinkPad Laptop
Total Sales             1200.0
Name: 6, dtype: object